[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
raffl = "Finb5eCnqTNm33ssqS2ofEnuoHzCmXaWfuXEn4HcaGRA"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
